<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<?php
	echo $this->tag->form(
		array(
			"messages/create",
			"autocomplete" => "off",
			"class" => "form-horizontal",
			"id" => "message-form"
		)
	);
?>

<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title">Добавление</h4>
</div>
<div class="modal-body">
		<?php echo $this->getContent(); ?>

		<div class="form-group">
			<label for="fieldName" class="col-sm-2 control-label">Name</label>
			<div class="col-sm-10">
				<?php echo $form->render("name", array("size" => 30, "class" => "form-control", "id" => "fieldName")); ?>
			</div>
		</div>

		<div class="form-group">
			<label for="fieldPhone" class="col-sm-2 control-label">Phone</label>
			<div class="col-sm-10">
				<?php echo $form->render("phone", array("size" => 30, "class" => "form-control", "id" => "fieldPhone", "placeholder"=>"+380XXXXXXXXX", 'maxLength'=>13)); ?>
			</div>
		</div>

		<div class="form-group">
			<label for="fieldEmail" class="col-sm-2 control-label">Email</label>
			<div class="col-sm-10">
				<?php echo $form->render("email", array("size" => 30, "class" => "form-control", "id" => "fieldEmail")); ?>
			</div>
		</div>

		<div class="form-group">
			<label for="fieldMessage" class="col-sm-2 control-label">Message</label>
			<div class="col-sm-10">
				<?php echo $form->render("message", array("cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldMessage")); ?>
			</div>
		</div>

		<?php //echo $form->render("csrf");
		?>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <?php echo $this->tag->submitButton(array("Save", "class" => "btn btn-primary")) ?>
</div>

<?php echo $this->tag->endForm(); ?>